# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=80)),
                ('gpu', models.CharField(blank=True, max_length=80)),
                ('ram', models.CharField(blank=True, max_length=80)),
                ('monitor', models.CharField(blank=True, max_length=80)),
                ('cpu', models.CharField(blank=True, max_length=80)),
                ('ssd', models.CharField(blank=True, max_length=80)),
                ('hdd', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
